name: rus_bal_dict
description: "Russian to Balkarian Dictionary App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  #ios иконки
  cupertino_icons: ^1.0.6
  #навигация
  go_router: ^14.0.2
  #стейт менеджер
  flutter_bloc: ^8.1.5
  #проигрывание аудио
  audioplayers: ^6.0.0
  #инъекция зависимостей (DI)
  get_it: ^7.7.0
  #генерация data классов
  freezed_annotation: ^2.4.1
  #для переопределения сравнивания объектов
  equatable: ^2.0.5
  #локальное хранилище
  shared_preferences: ^2.2.3
  #http запросы
  dio: ^5.4.3+1
  #result api подобный функционал для обработки ошибок
  either_dart: ^1.0.0
  #логирование
  talker: ^4.2.0
  #локальное хранилище (база данных) (в дальнейшем возможно заменить на drift/realm)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  #интерсептор для кэширования результатов запросов в сеть
  dio_cache_interceptor: ^3.5.0
  #для обращения в файловую систему (пока не нужно, возможно удалю)
  path_provider: ^2.1.3
  #удобные event transformers для flutter_bloc
  bloc_concurrency: ^0.2.5
  #плагин для получения информации об устройстве
  device_info_plus: ^10.1.0
  #шрифты от гугла
  google_fonts: ^6.2.1
  #svg иконки
  flutter_svg: ^2.0.10+1
  #html текст
  flutter_widget_from_html: ^0.15.1
  #набирать код восстановления
  pinput: ^5.0.0
  #работать с временем
  intl: ^0.19.0
  #вебвью
  webview_flutter: ^4.8.0
  url_launcher: ^6.3.0
  flutter_flavorizr: ^2.2.3
  dio_cache_interceptor_hive_store: ^3.2.2
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  mocktail: ^1.0.4

flutter:
  assets:
    - assets/images/
    - assets/images/favorites.svg
    - assets/images/play_audio.svg
    - assets/images/favorites_filled.svg
  uses-material-design: true

flavors:
  balrus:
    app:
      name: "BalRus App"
    android:
      applicationId: "ru.kbnc.balrus"  
    ios:
      bundleId: "ru.kbnc.balrus"
  rusbal:
    app:
      name: "RusBal App"
    android:
      applicationId: "ru.kbnc.rusbal"  
    ios:
      bundleId: "ru.kbnc.rusbal"