name: rus_bal_dict
description: "Russian to Balkarian Dictionary App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.6
  go_router: ^14.0.2
  flutter_bloc: ^8.1.5
  audioplayers: ^6.0.0
  get_it: ^7.7.0
  freezed_annotation: ^2.4.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  dio: ^5.4.3+1
  either_dart: ^1.0.0
  talker: ^4.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dio_cache_interceptor_hive_store: ^3.2.2
  dio_cache_interceptor: ^3.5.0
  path_provider: ^2.1.3
  bloc_concurrency: ^0.2.5
  device_info_plus: ^10.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  hive_generator: ^2.0.1

flutter:
  assets:
    - assets/images/
    - assets/images/favorites.svg
    - assets/images/play_audio.svg
    - assets/images/favorites_filled.svg
  uses-material-design: true