// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:rus_bal_dict/core/hive/favorite_word/favorite_word_hive_model.dart';
import 'package:rus_bal_dict/core/hive/settings/app_settings_hive.dart';
import 'package:rus_bal_dict/core/hive/word/word_hive_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(FavoriteWordHiveModelAdapter());
    registerAdapter(WordHiveModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(AppSettingsHiveModelAdapter());
    registerAdapter(FavoriteWordHiveModelAdapter());
    registerAdapter(WordHiveModelAdapter());
  }
}
